class UserPolicy < ApplicationPolicy
  def index?
    user.admin?
    true
  end


  def show
    user.present?
  end
  def create?
    user.present? && user.admin?
  end

  def new?
    user.present? && user.admin?
  end

  def update?
    user.present?&& user.admin?

  end

  def destroy?
    user.present? && user.admin?
  end


  # Inheriting from the application policy scope generated by the generator


  end
