User.create!([
  {email: "acolquerani@ameblo.jp", encrypted_password: "iNkuFU9IFGoE", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: nil, first_name: "Andras", last_name: "Colqueran", phone: nil, date_of_birth: nil, is_female: false},
  {email: "jorrah0@aol.com", encrypted_password: "95GtnFP", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "sales", first_name: "Joshua", last_name: "Orrah", phone: nil, date_of_birth: nil, is_female: false},
  {email: "sunita@mail.com", encrypted_password: "$2a$11$v4zIGm3TJF2LmX3w4CZ.jOLJlB8wNE08fKIP1HQJA3lD.4gxFr70q", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Marta", last_name: "Sunita", phone: nil, date_of_birth: nil, is_female: false},
  {email: "billy@mail.com", encrypted_password: "$2a$11$xf8aZ8VAdw9gUwFYDwv8Ye1TXTmgyEvRGmnJc/3uauPE8auibOIqu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Billy", last_name: "Dinh", phone: nil, date_of_birth: nil, is_female: false},
  {email: "marce@mail.com", encrypted_password: "$2a$11$IjFh680qbYdHXBrBUPRt5.OI7Mg2RlO3IxR8T7n8h881CkKZa1.U.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Marina", last_name: "Ondo", phone: "", date_of_birth: "2018-11-24 00:00:00", is_female: false},
  {email: "guanipa@mail.com", encrypted_password: "$2a$11$qU.IKAkloOZoPHPKwnXAJueyR0lxW2bFYIEeNSBy8Umqm8mDOfC1y", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "sales", first_name: "Santos", last_name: "Torealva", phone: nil, date_of_birth: nil, is_female: false},
  {email: "matutina@mail.com", encrypted_password: "$2a$11$oBHJYbxiAwsVSxTq24zbDedIfrDkBvmUrTBrYTavkEJx7UBpP1do.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Soraya", last_name: "Matutina", phone: nil, date_of_birth: nil, is_female: false},
  {email: "sandra@email.com", encrypted_password: "$2a$11$AtEWe2hfoJ4S3Dvvessh5.JVL6FPUZ7bf7bxMBqEJc0xLDDMsKpVC", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "sales", first_name: "Sandra", last_name: "Steward", phone: nil, date_of_birth: nil, is_female: false},
  {email: "idara@email.com", encrypted_password: "$2a$11$4W7eIfjc6jSISQCC6td3wuUbBgRc4qElqpJ3JUIVRD6wTOFBoZbVO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Clara", last_name: "Idara", phone: nil, date_of_birth: nil, is_female: false},
  {email: "mills@email.com", encrypted_password: "$2a$11$xw/g/pEayicbbEsy9OK29.Vh8YqON9xGlCP9oWYmi8.Y/U6ze48GO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "sales", first_name: "Sara", last_name: "mills", phone: nil, date_of_birth: nil, is_female: false},
  {email: "noara@mail.com", encrypted_password: "$2a$11$MZLoohd2cqvLivINXmdeD.1YLMDfM/hkTfNj7assvii3rtoY3DB.6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Carla", last_name: "Noara", phone: nil, date_of_birth: nil, is_female: false},
  {email: "laura@mail.com", encrypted_password: "$2a$11$WHo.6cwslpXoOrEq1v7SO.MKHFRWJSITYMfNawoEcuW0EIBhsajvO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Brittany", last_name: "Steward", phone: nil, date_of_birth: nil, is_female: false},
  {email: "barba@mail.com", encrypted_password: "$2a$11$OHKdjDFNZnpjasBJ8d0Ie.WprxpA1aopdYxe1d5TIw0wT/75DN14e", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "inventory", first_name: "Miguel", last_name: "Barbados", phone: nil, date_of_birth: nil, is_female: false},
  {email: "lee@mail.com", encrypted_password: "$2a$11$gAdsklzdHZeJo8OtqaJsfetQTlsldB0Q1j6lkZAs7IisWCBTMoA8W", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "inventory", first_name: "Bruce", last_name: "Lee", phone: nil, date_of_birth: nil, is_female: false},
  {email: "email@email.com", encrypted_password: "$2a$11$aLwkDWSoZUvBfOHZ/qDWhOGqKseBGXpO.vbK6pDVC.hpAokIqfrb.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "inventory", first_name: "Brian", last_name: "Santos", phone: nil, date_of_birth: nil, is_female: false},
  {email: "maanasa10@gmail.com", encrypted_password: "$2a$11$wBPDzq1rpJ5ou3eFrbADdOe9McCiKmZA32SShRgo/LvCDZrK2qkum", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "maanasa", last_name: "neralla", phone: nil, date_of_birth: nil, is_female: false},
  {email: "lolas@mail.com", encrypted_password: "$2a$11$Sa/JDVo.bqtHur1SYP6bkul0dClLWn9Ji4sbY6kP1sVr3DJNaibBO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Sonia", last_name: "Raquel", phone: nil, date_of_birth: nil, is_female: false},
  {email: "sandramail@mail.com", encrypted_password: "$2a$11$7kwm/Qanl1NLms5sqKrWz.TRW4bWyISKS251RcG8IURJSaAdmAZdS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "inventory", first_name: "lola", last_name: "Sandra", phone: nil, date_of_birth: nil, is_female: false},
  {email: "bibiana@mail.com", encrypted_password: "$2a$11$HX8HFlJVQa2xg9HNskenQeZKxu8W2IyF9T.m3vseYRCe/N.X6tYBm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Elsa", last_name: "Bibiana", phone: nil, date_of_birth: nil, is_female: false},
  {email: "epammail@mail.com", encrypted_password: "$2a$11$Av9suL/xBMa2Q1TSWPz09uTtTs5gbMCok4AELzMyctsEBWqGx38mS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Marcelo", last_name: "Epam", phone: nil, date_of_birth: nil, is_female: false},
  {email: "xoxo@mail.com", encrypted_password: "$2a$11$DEte3KBIbZM7VOKzI8FMKeDd2mWN/gt/.mwR9XHIRoBqr0n4BkUDi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Maele", last_name: "Ndong", phone: nil, date_of_birth: nil, is_female: false},
  {email: "sumila@mail.com", encrypted_password: "$2a$11$qpbGzEPXVYe.Uj.QcQaYW.ZED.c84Y62I9zCdwWjwZnCARxEjbHD2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Marta", last_name: "Sumila", phone: nil, date_of_birth: nil, is_female: false},
  {email: "mail@mail.com", encrypted_password: "$2a$11$pFEJ1iSJ0SH5ftvMfjr/9OKi72LdnIowRX8qaD.O7RZMI4Ei4l.hq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: nil, last_name: nil, phone: nil, date_of_birth: nil, is_female: false},
  {email: "marce@kmail.com", encrypted_password: "$2a$11$vxdU9wVS6XTeFfZmpyxZDuuk/iOp5B0FRj0q6sQOAg/HOakDepwf6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Marcelo", last_name: "Esono", phone: nil, date_of_birth: nil, is_female: false},
  {email: "gloria@mail.com", encrypted_password: "$2a$11$e3qOhnFbi1.2wDmWko0PKuMY0F74NcC41VRYG7bQDjblbvVkkt6kq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Maria Gloria", last_name: "Obono Bibang", phone: nil, date_of_birth: nil, is_female: false},
  {email: "ptilerf@skyrock.com", encrypted_password: "Jq5tRPx6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Prudi", last_name: "Tiler", phone: nil, date_of_birth: nil, is_female: false},
  {email: "fiacovuzzi5@myspace.com", encrypted_password: "P0OYyXlv0", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Fee", last_name: "Iacovuzzi", phone: nil, date_of_birth: nil, is_female: false},
  {email: "wmckoy8@nifty.com", encrypted_password: "5sOBolDFo23A", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Worthy", last_name: "McKoy", phone: nil, date_of_birth: nil, is_female: false},
  {email: "vskoggings2@mashable.com", encrypted_password: "2nPWwt2R", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Vaughn", last_name: "Skoggings", phone: nil, date_of_birth: nil, is_female: false},
  {email: "fsimanenko4@soundcloud.com", encrypted_password: "9rCxBvq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Freeman", last_name: "Simanenko", phone: nil, date_of_birth: nil, is_female: false},
  {email: "ckingdon1@intel.com", encrypted_password: "ubOQ3O8dRTeT", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Cletus", last_name: "Kingdon", phone: nil, date_of_birth: nil, is_female: false},
  {email: "eberi6@w3.org", encrypted_password: "mb5LrGM6mQJ0", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Emmalyn", last_name: "Beri", phone: nil, date_of_birth: nil, is_female: false},
  {email: "srobard7@moonfruit.com", encrypted_password: "CFoYHNED", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Sydney", last_name: "Robard", phone: nil, date_of_birth: nil, is_female: false},
  {email: "vsoggeeg@prweb.com", encrypted_password: "raPbJF", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Valaree", last_name: "Soggee", phone: nil, date_of_birth: nil, is_female: false},
  {email: "mcaulfield3@4shared.com", encrypted_password: "3X7XEWb", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Micah", last_name: "Caulfield", phone: nil, date_of_birth: nil, is_female: false},
  {email: "cadmansd@va.gov", encrypted_password: "W2v9vmad", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Conny", last_name: "Admans", phone: nil, date_of_birth: nil, is_female: false},
  {email: "jmanterfieldb@instagram.com", encrypted_password: "O5fVIYqCYJr", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Joyann", last_name: "Manterfield", phone: nil, date_of_birth: nil, is_female: false},
  {email: "khuddartj@howstuffworks.com", encrypted_password: "w9tyqDdoKk", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Koenraad", last_name: "Huddart", phone: nil, date_of_birth: nil, is_female: false},
  {email: "thallbirdk@shinystat.com", encrypted_password: "oYCEpSVVLw", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Tobey", last_name: "Hallbird", phone: nil, date_of_birth: nil, is_female: false},
  {email: "kdinsellh@mtv.com", encrypted_password: "7KsQVHko6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Keane", last_name: "Dinsell", phone: nil, date_of_birth: nil, is_female: false},
  {email: "wmeysl@meetup.com", encrypted_password: "OcIFDUMIEbx", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Westley", last_name: "Meys", phone: nil, date_of_birth: nil, is_female: false},
  {email: "kstoneleye@amazon.com", encrypted_password: "9cr9wY", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Klaus", last_name: "Stoneley", phone: nil, date_of_birth: nil, is_female: false},
  {email: "gsighardm@umich.edu", encrypted_password: "OQb9ru9Gcf5", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Gilbertina", last_name: "Sighard", phone: nil, date_of_birth: nil, is_female: false},
  {email: "vlyfen@github.com", encrypted_password: "qWOs77tHlmd", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Vachel", last_name: "Lyfe", phone: nil, date_of_birth: nil, is_female: false},
  {email: "lviggers9@weather.com", encrypted_password: "e8gXfXQiDok", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Lola", last_name: "Viggers", phone: nil, date_of_birth: nil, is_female: false},
  {email: "cgamlenc@nih.gov", encrypted_password: "Yfe7nDJqZ", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Chaddy", last_name: "Gamlen", phone: nil, date_of_birth: nil, is_female: false},
  {email: "aengar@si.edu", encrypted_password: "qicx6FH2D4yI", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Andi", last_name: "Enga", phone: nil, date_of_birth: nil, is_female: false},
  {email: "kpilipyaks@homestead.com", encrypted_password: "fq2iM4wW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Katherine", last_name: "Pilipyak", phone: nil, date_of_birth: nil, is_female: false},
  {email: "hpharoaho@mtv.com", encrypted_password: "AXZ7xbDZcG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Hadley", last_name: "Pharoah", phone: nil, date_of_birth: nil, is_female: false},
  {email: "jgodilingtonp@technorati.com", encrypted_password: "fsbqUfKD", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "finance", first_name: "Jard", last_name: "Godilington", phone: nil, date_of_birth: nil, is_female: false},
  {email: "lmoorsq@census.gov", encrypted_password: "6Ojwqugv", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Linoel", last_name: "Moors", phone: nil, date_of_birth: nil, is_female: false},
  {email: "kgraalmanu@salon.com", encrypted_password: "vfq1pahERa", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "admin", first_name: "Karlotta", last_name: "Graalman", phone: nil, date_of_birth: nil, is_female: false},
  {email: "tburnsidest@wunderground.com", encrypted_password: "9jG64gibMF", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, role: "agent", first_name: "Twyla", last_name: "Burnsides", phone: nil, date_of_birth: nil, is_female: false}
])
Customer.create!([
  {gender: "Female", first_name: "Sarah", last_name: "Brown", address: "4356 Street dr", email: "marta@mail.com", phone: "8659430302"},
  {gender: "Male", first_name: "Evin", last_name: "Dimitrie", address: "8536 Rutledge Center", email: "edimitrie0@reddit.com", phone: "269-425-4458"},
  {gender: "Female", first_name: "Corri", last_name: "Cabena", address: "22 Butterfield Alley", email: "ccabena1@mit.edu", phone: "645-859-8542"},
  {gender: "Female", first_name: "Estel", last_name: "McGennis", address: "578 Almo Center", email: "emcgennis2@ifeng.com", phone: "926-114-9188"},
  {gender: "Female", first_name: "Tamara", last_name: "Tolhurst", address: "0 Express Parkway", email: "ttolhurst3@tripadvisor.com", phone: "480-157-8732"},
  {gender: "Male", first_name: "Benedetto", last_name: "Frammingham", address: "84 Kensington Circle", email: "bframmingham4@mit.edu", phone: "620-828-9993"},
  {gender: "Female", first_name: "Karolina", last_name: "Roycraft", address: "3674 Westend Crossing", email: "kroycraft5@rakuten.co.jp", phone: "135-213-4177"},
  {gender: "Male", first_name: "Roderic", last_name: "Orrell", address: "1218 Paget Street", email: "rorrell6@auda.org.au", phone: "419-757-9059"},
  {gender: "Female", first_name: "Amalee", last_name: "Heard", address: "2897 Stang Court", email: "aheard7@yelp.com", phone: "373-305-9345"},
  {gender: "Female", first_name: "Nonna", last_name: "Hardwell", address: "4 Montana Junction", email: "nhardwell8@epa.gov", phone: "589-480-8403"},
  {gender: "Male", first_name: "Ave", last_name: "Phillpot", address: "09 Nobel Street", email: "aphillpot9@nasa.gov", phone: "114-778-7200"},
  {gender: "Female", first_name: "Bonni", last_name: "Clapson", address: "8941 Grover Terrace", email: "bclapsona@artisteer.com", phone: "397-487-4301"},
  {gender: "Male", first_name: "Reinaldo", last_name: "Hadye", address: "3 Blaine Drive", email: "rhadyeb@biblegateway.com", phone: "685-788-0059"},
  {gender: "Male", first_name: "Augustine", last_name: "Crush", address: "7282 Ridgeway Parkway", email: "acrushc@yellowpages.com", phone: "377-207-8148"},
  {gender: "Female", first_name: "Shannen", last_name: "Ramsier", address: "81 Cascade Road", email: "sramsierd@tripod.com", phone: "267-143-4330"},
  {gender: "Male", first_name: "Humfried", last_name: "Priestland", address: "4709 Lakeland Trail", email: "hpriestlande@shop-pro.jp", phone: "203-375-3753"},
  {gender: "Male", first_name: "Danny", last_name: "Thornewill", address: "4585 Almo Hill", email: "dthornewillf@amazon.co.jp", phone: "743-572-9620"},
  {gender: "Female", first_name: "Margaux", last_name: "Featherston", address: "5300 Lakewood Gardens Plaza", email: "mfeatherstong@chicagotribune.com", phone: "460-757-6394"},
  {gender: "Male", first_name: "Corbet", last_name: "Banaszewski", address: "92 Dapin Circle", email: "cbanaszewskih@tamu.edu", phone: "300-320-4950"},
  {gender: "Female", first_name: "Cindelyn", last_name: "Giannassi", address: "86142 Debra Park", email: "cgiannassii@shareasale.com", phone: "125-709-9351"},
  {gender: "Male", first_name: "Emilio", last_name: "Noore", address: "577 Corben Pass", email: "enoorej@rambler.ru", phone: "726-401-2332"},
  {gender: "Female", first_name: "Roda", last_name: "Vigus", address: "062 Bartillon Circle", email: "rvigusk@amazon.co.jp", phone: "518-696-9116"},
  {gender: "Female", first_name: "Beilul", last_name: "Martinie", address: "51247 Spohn Circle", email: "bmartiniel@flickr.com", phone: "594-944-7816"},
  {gender: "Female", first_name: "Ulrike", last_name: "Levett", address: "58 Duke Drive", email: "ulevettm@fotki.com", phone: "574-116-8787"},
  {gender: "Female", first_name: "Kora", last_name: "Draaisma", address: "324 Scofield Alley", email: "kdraaisman@lulu.com", phone: "943-374-4748"},
  {gender: "Female", first_name: "Janaye", last_name: "Milson", address: "556 Southridge Pass", email: "jmilsono@phpbb.com", phone: "660-125-3678"},
  {gender: "Female", first_name: "Patrica", last_name: "Levick", address: "7378 Express Alley", email: "plevickp@qq.com", phone: "543-141-5596"},
  {gender: "Male", first_name: "Aurthur", last_name: "Hathaway", address: "6226 Nevada Way", email: "ahathawayq@ed.gov", phone: "855-233-0041"},
  {gender: "Male", first_name: "Westbrook", last_name: "Bather", address: "29024 Karstens Plaza", email: "wbatherr@nbcnews.com", phone: "244-713-5019"},
  {gender: "Male", first_name: "Montgomery", last_name: "Furnival", address: "39754 Scofield Crossing", email: "mfurnivals@yellowbook.com", phone: "230-818-5038"},
  {gender: "Female", first_name: "Gwenneth", last_name: "Yegorov", address: "9021 Mallard Place", email: "gyegorovt@unesco.org", phone: "855-768-0443"},
  {gender: "Female", first_name: "Myrlene", last_name: "Treversh", address: "332 Golf Course Hill", email: "mtrevershu@blogs.com", phone: "244-202-8929"},
  {gender: "Male", first_name: "Aland", last_name: "Maggi", address: "537 Washington Trail", email: "amaggiv@blogger.com", phone: "844-841-0734"},
  {gender: "Male", first_name: "Casey", last_name: "Petschelt", address: "5088 Swallow Alley", email: "cpetscheltw@i2i.jp", phone: "647-815-8527"},
  {gender: "Male", first_name: "Rance", last_name: "McCulley", address: "048 Melody Lane", email: "rmcculleyx@chicagotribune.com", phone: "201-202-4751"},
  {gender: "Female", first_name: "Laurella", last_name: "Athey", address: "23391 Golf Course Junction", email: "latheyy@angelfire.com", phone: "482-396-4390"},
  {gender: "Male", first_name: "Alfonse", last_name: "Palk", address: "62 Fremont Park", email: "apalkz@aboutads.info", phone: "667-567-7656"},
  {gender: "Female", first_name: "Cathy", last_name: "Inder", address: "904 Vermont Street", email: "cinder10@utexas.edu", phone: "437-430-0536"},
  {gender: "Female", first_name: "Gypsy", last_name: "Dilks", address: "78 Cody Place", email: "gdilks11@amazon.co.uk", phone: "170-827-1212"},
  {gender: "Female", first_name: "Faun", last_name: "Burgess", address: "29 Melody Terrace", email: "fburgess12@bloglovin.com", phone: "599-125-6001"},
  {gender: "Male", first_name: "Winston", last_name: "de Voiels", address: "91 Maple Circle", email: "wdevoiels13@ezinearticles.com", phone: "343-220-9981"},
  {gender: "Male", first_name: "Shurlock", last_name: "Grocutt", address: "4 Mayfield Plaza", email: "sgrocutt14@time.com", phone: "699-439-1629"},
  {gender: "Female", first_name: "Dorthy", last_name: "Tunnick", address: "070 Walton Lane", email: "dtunnick15@nsw.gov.au", phone: "820-174-2569"},
  {gender: "Female", first_name: "Hanni", last_name: "Baudet", address: "665 Michigan Crossing", email: "hbaudet16@alibaba.com", phone: "514-630-1110"},
  {gender: "Male", first_name: "Mendie", last_name: "Joel", address: "59 Lakewood Crossing", email: "mjoel17@utexas.edu", phone: "599-912-7846"},
  {gender: "Female", first_name: "Pia", last_name: "Cod", address: "94216 Washington Plaza", email: "pcod18@reverbnation.com", phone: "994-488-5992"},
  {gender: "Male", first_name: "Euell", last_name: "Silverwood", address: "9106 Pierstorff Trail", email: "esilverwood19@amazon.com", phone: "275-347-8170"},
  {gender: "Female", first_name: "Roxy", last_name: "Moral", address: "25243 Di Loreto Circle", email: "rmoral1a@4shared.com", phone: "468-185-0985"},
  {gender: "Male", first_name: "Merrill", last_name: "Jean", address: "7 Vernon Center", email: "mjean1b@pbs.org", phone: "851-893-1590"},
  {gender: "Female", first_name: "Odelia", last_name: "Rowly", address: "73990 Ryan Place", email: "orowly1c@squidoo.com", phone: "760-929-2426"},
  {gender: "Male", first_name: "Adolf", last_name: "Cartmill", address: "1 Barby Junction", email: "acartmill1d@nydailynews.com", phone: "207-124-7417"},
  {gender: "Male", first_name: "Goran", last_name: "McArt", address: "2507 Nobel Park", email: "gmcart1e@nature.com", phone: "116-332-6789"},
  {gender: "Male", first_name: "Donavon", last_name: "Riddle", address: "2 Tony Avenue", email: "driddle1f@businessweek.com", phone: "602-790-5797"},
  {gender: "Male", first_name: "Jordon", last_name: "Brumpton", address: "5967 8th Trail", email: "jbrumpton1g@zdnet.com", phone: "334-806-2886"},
  {gender: "Male", first_name: "Edmund", last_name: "Olenov", address: "38765 Rutledge Crossing", email: "eolenov1h@etsy.com", phone: "228-907-1181"},
  {gender: "Female", first_name: "Edi", last_name: "Kleanthous", address: "94 Oak Valley Crossing", email: "ekleanthous1i@google.fr", phone: "650-627-1759"},
  {gender: "Male", first_name: "Cole", last_name: "Bromley", address: "3 Ronald Regan Place", email: "cbromley1j@google.com.au", phone: "344-787-4664"},
  {gender: "Male", first_name: "Morley", last_name: "Lempke", address: "41 Fieldstone Point", email: "mlempke1k@flickr.com", phone: "596-160-4440"},
  {gender: "Female", first_name: "Fina", last_name: "Jonk", address: "5408 Sutteridge Parkway", email: "fjonk1l@networksolutions.com", phone: "693-816-2526"},
  {gender: "Female", first_name: "Emelyne", last_name: "Byllam", address: "03 Lindbergh Alley", email: "ebyllam1m@youtu.be", phone: "831-487-1340"},
  {gender: "Male", first_name: "Vassily", last_name: "Whifen", address: "7 Reinke Circle", email: "vwhifen1n@github.com", phone: "896-805-1536"},
  {gender: "Male", first_name: "Pablo", last_name: "Scott", address: "625 Victoria Pass", email: "pscott1o@chronoengine.com", phone: "368-520-5794"},
  {gender: "Male", first_name: "Raff", last_name: "Sheivels", address: "793 Maywood Circle", email: "rsheivels1p@imageshack.us", phone: "818-544-2080"},
  {gender: "Female", first_name: "Clemence", last_name: "Chaise", address: "8 Magdeline Terrace", email: "cchaise1q@whitehouse.gov", phone: "859-863-1833"},
  {gender: "Male", first_name: "Moises", last_name: "Fernant", address: "9 School Way", email: "mfernant1r@google.cn", phone: "185-905-3364"},
  {gender: "Female", first_name: "Mia", last_name: "FitzGilbert", address: "3 Morrow Junction", email: "mfitzgilbert1s@howstuffworks.com", phone: "359-129-1124"},
  {gender: "Female", first_name: "Flossy", last_name: "Ilett", address: "44726 Beilfuss Crossing", email: "filett1t@ted.com", phone: "315-254-3649"},
  {gender: "Male", first_name: "Carver", last_name: "Suatt", address: "528 Crownhardt Road", email: "csuatt1u@omniture.com", phone: "657-938-6508"},
  {gender: "Male", first_name: "Clement", last_name: "Dulling", address: "7 Lukken Place", email: "cdulling1v@businessinsider.com", phone: "746-734-3833"},
  {gender: "Male", first_name: "Lawton", last_name: "Sargison", address: "3491 Texas Point", email: "lsargison1w@list-manage.com", phone: "905-895-0180"},
  {gender: "Female", first_name: "Roxie", last_name: "Gentzsch", address: "54207 Buhler Junction", email: "rgentzsch1x@issuu.com", phone: "707-977-6520"},
  {gender: "Male", first_name: "Ezequiel", last_name: "Mullane", address: "2 Scoville Drive", email: "emullane1y@hp.com", phone: "230-885-9155"},
  {gender: "Female", first_name: "Delphinia", last_name: "Aves", address: "86118 Porter Pass", email: "daves1z@guardian.co.uk", phone: "199-596-0620"},
  {gender: "Female", first_name: "Johna", last_name: "Rown", address: "516 Eagle Crest Road", email: "jrown20@usgs.gov", phone: "290-769-3924"},
  {gender: "Female", first_name: "Erena", last_name: "Garstan", address: "914 Menomonie Road", email: "egarstan21@instagram.com", phone: "749-905-0223"},
  {gender: "Male", first_name: "Rudyard", last_name: "Courtenay", address: "137 Nova Trail", email: "rcourtenay22@harvard.edu", phone: "559-214-6978"},
  {gender: "Male", first_name: "Rudolfo", last_name: "Petruszka", address: "542 Everett Street", email: "rpetruszka23@nps.gov", phone: "382-195-1233"},
  {gender: "Female", first_name: "Dorey", last_name: "Glas", address: "069 Riverside Trail", email: "dglas24@buzzfeed.com", phone: "241-298-7476"},
  {gender: "Female", first_name: "Missy", last_name: "Priter", address: "61605 Russell Crossing", email: "mpriter25@so-net.ne.jp", phone: "208-991-4823"},
  {gender: "Male", first_name: "Kit", last_name: "Lightwing", address: "20 Sutteridge Road", email: "klightwing26@vk.com", phone: "406-234-0073"},
  {gender: "Female", first_name: "Rosene", last_name: "Hissett", address: "975 Hauk Circle", email: "rhissett27@dedecms.com", phone: "564-775-4429"},
  {gender: "Male", first_name: "Porter", last_name: "Breeze", address: "046 Beilfuss Lane", email: "pbreeze28@msu.edu", phone: "737-772-8326"},
  {gender: "Male", first_name: "Reilly", last_name: "Marrian", address: "16 Kings Alley", email: "rmarrian29@wp.com", phone: "280-637-1232"},
  {gender: "Female", first_name: "Fredelia", last_name: "Drage", address: "56441 Thompson Crossing", email: "fdrage2a@miitbeian.gov.cn", phone: "257-323-1069"},
  {gender: "Male", first_name: "Haroun", last_name: "Bucknell", address: "3610 Tony Circle", email: "hbucknell2b@youku.com", phone: "641-451-6396"},
  {gender: "Male", first_name: "Emanuel", last_name: "Gehring", address: "95880 Melby Way", email: "egehring2c@cargocollective.com", phone: "992-561-6767"},
  {gender: "Male", first_name: "Micheil", last_name: "Sands-Allan", address: "05 Northridge Avenue", email: "msandsallan2d@bandcamp.com", phone: "349-333-7486"},
  {gender: "Female", first_name: "Tammie", last_name: "Baalham", address: "479 Eliot Point", email: "tbaalham2e@desdev.cn", phone: "900-298-9727"},
  {gender: "Male", first_name: "Casar", last_name: "MacMenamin", address: "47 Pine View Crossing", email: "cmacmenamin2f@weebly.com", phone: "301-721-9730"},
  {gender: "Female", first_name: "Katrina", last_name: "De Ortega", address: "7 Shasta Street", email: "kdeortega2g@ehow.com", phone: "927-993-6700"},
  {gender: "Female", first_name: "Dorella", last_name: "Venners", address: "22 Dahle Lane", email: "dvenners2h@google.fr", phone: "676-107-6095"},
  {gender: "Female", first_name: "Niki", last_name: "Gilham", address: "33 Carpenter Center", email: "ngilham2i@marketwatch.com", phone: "119-737-7444"},
  {gender: "Female", first_name: "Dela", last_name: "Domerc", address: "060 Blackbird Street", email: "ddomerc2j@jalbum.net", phone: "645-963-7064"},
  {gender: "Male", first_name: "Carroll", last_name: "Skipworth", address: "98298 Green Avenue", email: "cskipworth2k@foxnews.com", phone: "299-385-8296"},
  {gender: "Male", first_name: "Alonso", last_name: "Baddow", address: "90840 Green Ridge Parkway", email: "abaddow2l@joomla.org", phone: "857-624-1420"},
  {gender: "Male", first_name: "Umberto", last_name: "Brettell", address: "7 Northwestern Court", email: "ubrettell2m@wiley.com", phone: "303-613-1443"},
  {gender: "Female", first_name: "Cookie", last_name: "Swalough", address: "20 Gateway Way", email: "cswalough2n@dailymail.co.uk", phone: "408-946-8200"},
  {gender: "Male", first_name: "Wait", last_name: "Edlington", address: "8 2nd Trail", email: "wedlington2o@naver.com", phone: "253-469-2380"},
  {gender: "Male", first_name: "Kaleb", last_name: "Churchard", address: "6 Clyde Gallagher Plaza", email: "kchurchard2p@altervista.org", phone: "964-377-1483"},
  {gender: "Male", first_name: "Hank", last_name: "Lindenbaum", address: "342 Moulton Alley", email: "hlindenbaum2q@altervista.org", phone: "121-702-1502"},
  {gender: "Male", first_name: "Hilton", last_name: "Hartop", address: "41246 Fallview Drive", email: "hhartop2r@alexa.com", phone: "232-290-8720"},
  {gender: "Female", first_name: "Sarah", last_name: "Brown", address: "4356 Street dr", email: "marta@mail.com", phone: "8659430302"},
  {gender: "Male", first_name: "Evin", last_name: "Dimitrie", address: "8536 Rutledge Center", email: "edimitrie0@reddit.com", phone: "269-425-4458"},
  {gender: "Female", first_name: "Corri", last_name: "Cabena", address: "22 Butterfield Alley", email: "ccabena1@mit.edu", phone: "645-859-8542"},
  {gender: "Female", first_name: "Estel", last_name: "McGennis", address: "578 Almo Center", email: "emcgennis2@ifeng.com", phone: "926-114-9188"},
  {gender: "Female", first_name: "Tamara", last_name: "Tolhurst", address: "0 Express Parkway", email: "ttolhurst3@tripadvisor.com", phone: "480-157-8732"},
  {gender: "Male", first_name: "Benedetto", last_name: "Frammingham", address: "84 Kensington Circle", email: "bframmingham4@mit.edu", phone: "620-828-9993"},
  {gender: "Female", first_name: "Karolina", last_name: "Roycraft", address: "3674 Westend Crossing", email: "kroycraft5@rakuten.co.jp", phone: "135-213-4177"},
  {gender: "Male", first_name: "Roderic", last_name: "Orrell", address: "1218 Paget Street", email: "rorrell6@auda.org.au", phone: "419-757-9059"},
  {gender: "Female", first_name: "Amalee", last_name: "Heard", address: "2897 Stang Court", email: "aheard7@yelp.com", phone: "373-305-9345"},
  {gender: "Female", first_name: "Nonna", last_name: "Hardwell", address: "4 Montana Junction", email: "nhardwell8@epa.gov", phone: "589-480-8403"},
  {gender: "Male", first_name: "Ave", last_name: "Phillpot", address: "09 Nobel Street", email: "aphillpot9@nasa.gov", phone: "114-778-7200"},
  {gender: "Female", first_name: "Bonni", last_name: "Clapson", address: "8941 Grover Terrace", email: "bclapsona@artisteer.com", phone: "397-487-4301"},
  {gender: "Male", first_name: "Reinaldo", last_name: "Hadye", address: "3 Blaine Drive", email: "rhadyeb@biblegateway.com", phone: "685-788-0059"},
  {gender: "Male", first_name: "Augustine", last_name: "Crush", address: "7282 Ridgeway Parkway", email: "acrushc@yellowpages.com", phone: "377-207-8148"},
  {gender: "Female", first_name: "Shannen", last_name: "Ramsier", address: "81 Cascade Road", email: "sramsierd@tripod.com", phone: "267-143-4330"},
  {gender: "Male", first_name: "Humfried", last_name: "Priestland", address: "4709 Lakeland Trail", email: "hpriestlande@shop-pro.jp", phone: "203-375-3753"},
  {gender: "Male", first_name: "Danny", last_name: "Thornewill", address: "4585 Almo Hill", email: "dthornewillf@amazon.co.jp", phone: "743-572-9620"},
  {gender: "Female", first_name: "Margaux", last_name: "Featherston", address: "5300 Lakewood Gardens Plaza", email: "mfeatherstong@chicagotribune.com", phone: "460-757-6394"},
  {gender: "Male", first_name: "Corbet", last_name: "Banaszewski", address: "92 Dapin Circle", email: "cbanaszewskih@tamu.edu", phone: "300-320-4950"},
  {gender: "Female", first_name: "Cindelyn", last_name: "Giannassi", address: "86142 Debra Park", email: "cgiannassii@shareasale.com", phone: "125-709-9351"},
  {gender: "Male", first_name: "Emilio", last_name: "Noore", address: "577 Corben Pass", email: "enoorej@rambler.ru", phone: "726-401-2332"},
  {gender: "Female", first_name: "Roda", last_name: "Vigus", address: "062 Bartillon Circle", email: "rvigusk@amazon.co.jp", phone: "518-696-9116"},
  {gender: "Female", first_name: "Beilul", last_name: "Martinie", address: "51247 Spohn Circle", email: "bmartiniel@flickr.com", phone: "594-944-7816"},
  {gender: "Female", first_name: "Ulrike", last_name: "Levett", address: "58 Duke Drive", email: "ulevettm@fotki.com", phone: "574-116-8787"},
  {gender: "Female", first_name: "Kora", last_name: "Draaisma", address: "324 Scofield Alley", email: "kdraaisman@lulu.com", phone: "943-374-4748"},
  {gender: "Female", first_name: "Janaye", last_name: "Milson", address: "556 Southridge Pass", email: "jmilsono@phpbb.com", phone: "660-125-3678"},
  {gender: "Female", first_name: "Patrica", last_name: "Levick", address: "7378 Express Alley", email: "plevickp@qq.com", phone: "543-141-5596"},
  {gender: "Male", first_name: "Aurthur", last_name: "Hathaway", address: "6226 Nevada Way", email: "ahathawayq@ed.gov", phone: "855-233-0041"},
  {gender: "Male", first_name: "Westbrook", last_name: "Bather", address: "29024 Karstens Plaza", email: "wbatherr@nbcnews.com", phone: "244-713-5019"},
  {gender: "Male", first_name: "Montgomery", last_name: "Furnival", address: "39754 Scofield Crossing", email: "mfurnivals@yellowbook.com", phone: "230-818-5038"},
  {gender: "Female", first_name: "Gwenneth", last_name: "Yegorov", address: "9021 Mallard Place", email: "gyegorovt@unesco.org", phone: "855-768-0443"},
  {gender: "Female", first_name: "Myrlene", last_name: "Treversh", address: "332 Golf Course Hill", email: "mtrevershu@blogs.com", phone: "244-202-8929"},
  {gender: "Male", first_name: "Aland", last_name: "Maggi", address: "537 Washington Trail", email: "amaggiv@blogger.com", phone: "844-841-0734"},
  {gender: "Male", first_name: "Casey", last_name: "Petschelt", address: "5088 Swallow Alley", email: "cpetscheltw@i2i.jp", phone: "647-815-8527"},
  {gender: "Male", first_name: "Rance", last_name: "McCulley", address: "048 Melody Lane", email: "rmcculleyx@chicagotribune.com", phone: "201-202-4751"},
  {gender: "Female", first_name: "Laurella", last_name: "Athey", address: "23391 Golf Course Junction", email: "latheyy@angelfire.com", phone: "482-396-4390"},
  {gender: "Male", first_name: "Alfonse", last_name: "Palk", address: "62 Fremont Park", email: "apalkz@aboutads.info", phone: "667-567-7656"},
  {gender: "Female", first_name: "Cathy", last_name: "Inder", address: "904 Vermont Street", email: "cinder10@utexas.edu", phone: "437-430-0536"},
  {gender: "Female", first_name: "Gypsy", last_name: "Dilks", address: "78 Cody Place", email: "gdilks11@amazon.co.uk", phone: "170-827-1212"},
  {gender: "Female", first_name: "Faun", last_name: "Burgess", address: "29 Melody Terrace", email: "fburgess12@bloglovin.com", phone: "599-125-6001"},
  {gender: "Male", first_name: "Winston", last_name: "de Voiels", address: "91 Maple Circle", email: "wdevoiels13@ezinearticles.com", phone: "343-220-9981"},
  {gender: "Male", first_name: "Shurlock", last_name: "Grocutt", address: "4 Mayfield Plaza", email: "sgrocutt14@time.com", phone: "699-439-1629"},
  {gender: "Female", first_name: "Dorthy", last_name: "Tunnick", address: "070 Walton Lane", email: "dtunnick15@nsw.gov.au", phone: "820-174-2569"},
  {gender: "Female", first_name: "Hanni", last_name: "Baudet", address: "665 Michigan Crossing", email: "hbaudet16@alibaba.com", phone: "514-630-1110"},
  {gender: "Male", first_name: "Mendie", last_name: "Joel", address: "59 Lakewood Crossing", email: "mjoel17@utexas.edu", phone: "599-912-7846"},
  {gender: "Female", first_name: "Pia", last_name: "Cod", address: "94216 Washington Plaza", email: "pcod18@reverbnation.com", phone: "994-488-5992"},
  {gender: "Male", first_name: "Euell", last_name: "Silverwood", address: "9106 Pierstorff Trail", email: "esilverwood19@amazon.com", phone: "275-347-8170"},
  {gender: "Female", first_name: "Roxy", last_name: "Moral", address: "25243 Di Loreto Circle", email: "rmoral1a@4shared.com", phone: "468-185-0985"},
  {gender: "Male", first_name: "Merrill", last_name: "Jean", address: "7 Vernon Center", email: "mjean1b@pbs.org", phone: "851-893-1590"},
  {gender: "Female", first_name: "Odelia", last_name: "Rowly", address: "73990 Ryan Place", email: "orowly1c@squidoo.com", phone: "760-929-2426"},
  {gender: "Male", first_name: "Adolf", last_name: "Cartmill", address: "1 Barby Junction", email: "acartmill1d@nydailynews.com", phone: "207-124-7417"},
  {gender: "Male", first_name: "Goran", last_name: "McArt", address: "2507 Nobel Park", email: "gmcart1e@nature.com", phone: "116-332-6789"},
  {gender: "Male", first_name: "Donavon", last_name: "Riddle", address: "2 Tony Avenue", email: "driddle1f@businessweek.com", phone: "602-790-5797"},
  {gender: "Male", first_name: "Jordon", last_name: "Brumpton", address: "5967 8th Trail", email: "jbrumpton1g@zdnet.com", phone: "334-806-2886"},
  {gender: "Male", first_name: "Edmund", last_name: "Olenov", address: "38765 Rutledge Crossing", email: "eolenov1h@etsy.com", phone: "228-907-1181"},
  {gender: "Female", first_name: "Edi", last_name: "Kleanthous", address: "94 Oak Valley Crossing", email: "ekleanthous1i@google.fr", phone: "650-627-1759"},
  {gender: "Male", first_name: "Cole", last_name: "Bromley", address: "3 Ronald Regan Place", email: "cbromley1j@google.com.au", phone: "344-787-4664"},
  {gender: "Male", first_name: "Morley", last_name: "Lempke", address: "41 Fieldstone Point", email: "mlempke1k@flickr.com", phone: "596-160-4440"},
  {gender: "Female", first_name: "Fina", last_name: "Jonk", address: "5408 Sutteridge Parkway", email: "fjonk1l@networksolutions.com", phone: "693-816-2526"},
  {gender: "Female", first_name: "Emelyne", last_name: "Byllam", address: "03 Lindbergh Alley", email: "ebyllam1m@youtu.be", phone: "831-487-1340"},
  {gender: "Male", first_name: "Vassily", last_name: "Whifen", address: "7 Reinke Circle", email: "vwhifen1n@github.com", phone: "896-805-1536"},
  {gender: "Male", first_name: "Pablo", last_name: "Scott", address: "625 Victoria Pass", email: "pscott1o@chronoengine.com", phone: "368-520-5794"},
  {gender: "Male", first_name: "Raff", last_name: "Sheivels", address: "793 Maywood Circle", email: "rsheivels1p@imageshack.us", phone: "818-544-2080"},
  {gender: "Female", first_name: "Clemence", last_name: "Chaise", address: "8 Magdeline Terrace", email: "cchaise1q@whitehouse.gov", phone: "859-863-1833"},
  {gender: "Male", first_name: "Moises", last_name: "Fernant", address: "9 School Way", email: "mfernant1r@google.cn", phone: "185-905-3364"},
  {gender: "Female", first_name: "Mia", last_name: "FitzGilbert", address: "3 Morrow Junction", email: "mfitzgilbert1s@howstuffworks.com", phone: "359-129-1124"},
  {gender: "Female", first_name: "Flossy", last_name: "Ilett", address: "44726 Beilfuss Crossing", email: "filett1t@ted.com", phone: "315-254-3649"},
  {gender: "Male", first_name: "Carver", last_name: "Suatt", address: "528 Crownhardt Road", email: "csuatt1u@omniture.com", phone: "657-938-6508"},
  {gender: "Male", first_name: "Clement", last_name: "Dulling", address: "7 Lukken Place", email: "cdulling1v@businessinsider.com", phone: "746-734-3833"},
  {gender: "Male", first_name: "Lawton", last_name: "Sargison", address: "3491 Texas Point", email: "lsargison1w@list-manage.com", phone: "905-895-0180"},
  {gender: "Female", first_name: "Roxie", last_name: "Gentzsch", address: "54207 Buhler Junction", email: "rgentzsch1x@issuu.com", phone: "707-977-6520"},
  {gender: "Male", first_name: "Ezequiel", last_name: "Mullane", address: "2 Scoville Drive", email: "emullane1y@hp.com", phone: "230-885-9155"},
  {gender: "Female", first_name: "Delphinia", last_name: "Aves", address: "86118 Porter Pass", email: "daves1z@guardian.co.uk", phone: "199-596-0620"},
  {gender: "Female", first_name: "Johna", last_name: "Rown", address: "516 Eagle Crest Road", email: "jrown20@usgs.gov", phone: "290-769-3924"},
  {gender: "Female", first_name: "Erena", last_name: "Garstan", address: "914 Menomonie Road", email: "egarstan21@instagram.com", phone: "749-905-0223"},
  {gender: "Male", first_name: "Rudyard", last_name: "Courtenay", address: "137 Nova Trail", email: "rcourtenay22@harvard.edu", phone: "559-214-6978"},
  {gender: "Male", first_name: "Rudolfo", last_name: "Petruszka", address: "542 Everett Street", email: "rpetruszka23@nps.gov", phone: "382-195-1233"},
  {gender: "Female", first_name: "Dorey", last_name: "Glas", address: "069 Riverside Trail", email: "dglas24@buzzfeed.com", phone: "241-298-7476"},
  {gender: "Female", first_name: "Missy", last_name: "Priter", address: "61605 Russell Crossing", email: "mpriter25@so-net.ne.jp", phone: "208-991-4823"},
  {gender: "Male", first_name: "Kit", last_name: "Lightwing", address: "20 Sutteridge Road", email: "klightwing26@vk.com", phone: "406-234-0073"},
  {gender: "Female", first_name: "Rosene", last_name: "Hissett", address: "975 Hauk Circle", email: "rhissett27@dedecms.com", phone: "564-775-4429"},
  {gender: "Male", first_name: "Porter", last_name: "Breeze", address: "046 Beilfuss Lane", email: "pbreeze28@msu.edu", phone: "737-772-8326"},
  {gender: "Male", first_name: "Reilly", last_name: "Marrian", address: "16 Kings Alley", email: "rmarrian29@wp.com", phone: "280-637-1232"},
  {gender: "Female", first_name: "Fredelia", last_name: "Drage", address: "56441 Thompson Crossing", email: "fdrage2a@miitbeian.gov.cn", phone: "257-323-1069"},
  {gender: "Male", first_name: "Haroun", last_name: "Bucknell", address: "3610 Tony Circle", email: "hbucknell2b@youku.com", phone: "641-451-6396"},
  {gender: "Male", first_name: "Emanuel", last_name: "Gehring", address: "95880 Melby Way", email: "egehring2c@cargocollective.com", phone: "992-561-6767"},
  {gender: "Male", first_name: "Micheil", last_name: "Sands-Allan", address: "05 Northridge Avenue", email: "msandsallan2d@bandcamp.com", phone: "349-333-7486"},
  {gender: "Female", first_name: "Tammie", last_name: "Baalham", address: "479 Eliot Point", email: "tbaalham2e@desdev.cn", phone: "900-298-9727"},
  {gender: "Male", first_name: "Casar", last_name: "MacMenamin", address: "47 Pine View Crossing", email: "cmacmenamin2f@weebly.com", phone: "301-721-9730"},
  {gender: "Female", first_name: "Katrina", last_name: "De Ortega", address: "7 Shasta Street", email: "kdeortega2g@ehow.com", phone: "927-993-6700"},
  {gender: "Female", first_name: "Dorella", last_name: "Venners", address: "22 Dahle Lane", email: "dvenners2h@google.fr", phone: "676-107-6095"},
  {gender: "Female", first_name: "Niki", last_name: "Gilham", address: "33 Carpenter Center", email: "ngilham2i@marketwatch.com", phone: "119-737-7444"},
  {gender: "Female", first_name: "Dela", last_name: "Domerc", address: "060 Blackbird Street", email: "ddomerc2j@jalbum.net", phone: "645-963-7064"},
  {gender: "Male", first_name: "Carroll", last_name: "Skipworth", address: "98298 Green Avenue", email: "cskipworth2k@foxnews.com", phone: "299-385-8296"},
  {gender: "Male", first_name: "Alonso", last_name: "Baddow", address: "90840 Green Ridge Parkway", email: "abaddow2l@joomla.org", phone: "857-624-1420"},
  {gender: "Male", first_name: "Umberto", last_name: "Brettell", address: "7 Northwestern Court", email: "ubrettell2m@wiley.com", phone: "303-613-1443"},
  {gender: "Female", first_name: "Cookie", last_name: "Swalough", address: "20 Gateway Way", email: "cswalough2n@dailymail.co.uk", phone: "408-946-8200"},
  {gender: "Male", first_name: "Wait", last_name: "Edlington", address: "8 2nd Trail", email: "wedlington2o@naver.com", phone: "253-469-2380"},
  {gender: "Male", first_name: "Kaleb", last_name: "Churchard", address: "6 Clyde Gallagher Plaza", email: "kchurchard2p@altervista.org", phone: "964-377-1483"},
  {gender: "Male", first_name: "Hank", last_name: "Lindenbaum", address: "342 Moulton Alley", email: "hlindenbaum2q@altervista.org", phone: "121-702-1502"},
  {gender: "Male", first_name: "Hilton", last_name: "Hartop", address: "41246 Fallview Drive", email: "hhartop2r@alexa.com", phone: "232-290-8720"}
])
Vehicle.create!([
  {vin: "WBA3B5C59FF500799", year: 2008, make: "Volvo", model: "S60", color: "Puce", wholesale_price: 6659.0, cover_photo: nil},
  {vin: "KNADM4A37C6833668", year: 2007, make: "Lincoln", model: "Continental Mark", color: "red", wholesale_price: 69504.0, cover_photo: nil},
  {vin: "kerpt45op64p5ip3w", year: 2006, make: "Dodge", model: "Rio", color: "blue", wholesale_price: 7067.0, cover_photo: nil},
  {vin: "54054rg0dfig4350", year: 2008, make: "Dodge", model: "Alero", color: "white", wholesale_price: 95640.0, cover_photo: nil},
  {vin: "609504rpokgrpok", year: 2007, make: "Chevrolet", model: "S60", color: "Dark Blue", wholesale_price: 69540.0, cover_photo: nil},
  {vin: "tdgkdfk45l345", year: 2018, make: "Lincoln", model: "Concorde", color: "black", wholesale_price: 6794.0, cover_photo: nil},
  {vin: "598u54093sfdiujk", year: 2001, make: "Kia", model: "Alero", color: "yellow", wholesale_price: 9440.0, cover_photo: nil},
  {vin: "6005434", year: 2004, make: "Land Rover", model: "Concorde", color: "grey", wholesale_price: 2000.0, cover_photo: nil},
  {vin: "549043rejihdsfds09", year: 2004, make: "Suzuki", model: "Rio", color: "Shiny blue", wholesale_price: 3000.0, cover_photo: nil},
  {vin: "4305ererj", year: 2005, make: "Chrystler", model: "XL-7", color: "Red", wholesale_price: 8000.0, cover_photo: nil}
])
